src/fraisBundle/Entity/Utilisateur.php
<?php

namespace fraisBundle\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use FOS\UserBundle\Model\UserInterface;

/**
 * @ORM\Entity(repositoryClass="fraisBundle\Repository\UtilisateurRepository")
 * @ORM\Table(name="utilisateur")
 * @ORM\HasLifecycleCallbacks()
 */
class Utilisateur extends BaseUser
{
    const ROLE_UTILISATEUR = "ROLE_UTILISATEUR";
    const ROLE_COMPTABLE = "ROLE_COMPTABLE";
    const ROLE_ADMINISTRATEUR = "ROLE_ADMINISTRATEUR";
    public $type;
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;
    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=30, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="prenom", type="string", length=30, nullable=false)
     */
    private $prenom;

    /**
     * @var string
     *
     * @ORM\Column(name="adresse", type="string", length=30, nullable=false)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(name="cp", type="string", length=5, nullable=false)
     */
    private $cp;

    /**
     * @var string
     *
     * @ORM\Column(name="ville", type="string", length=30, nullable=false)
     */
    private $ville;

    /**
     * @var string
     *
     * @ORM\Column(name="number", type="string", length=10, nullable=true)
     */
    private $number;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_embauche", type="date", nullable=false)
     */
    private $dateEmbauche;


    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="fraisBundle\Entity\FicheFrais", mappedBy="utilisateur")
     */
    private $lesFiches;

    public static function getRolesAvailable()
    {
        return array(
            self::ROLE_UTILISATEUR => 'Utilisateur',
            self::ROLE_ADMINISTRATEUR => 'Administrateur',
            self::ROLE_COMPTABLE => 'Comptable'
        );
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return $this
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get prenom
     *
     * @return string
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Set prenom
     *
     * @param string $prenom
     *
     * @return $this
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return string
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set adresse
     *
     * @param string $adresse
     *
     * @return $this
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get cp
     *
     * @return string
     */
    public function getCp()
    {
        return $this->cp;
    }

    /**
     * Set cp
     *
     * @param string $cp
     *
     * @return $this
     */
    public function setCp($cp)
    {
        $this->cp = $cp;

        return $this;
    }

    /**
     * Get ville
     *
     * @return string
     */
    public function getVille()
    {
        return $this->ville;
    }

    /**
     * Set ville
     *
     * @param string $ville
     *
     * @return $this
     */
    public function setVille($ville)
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * Get dateEmbauche
     *
     * @return \DateTime
     */
    public function getDateEmbauche()
    {
        return $this->dateEmbauche;
    }

    /**
     * Set dateEmbauche
     *
     * @param \DateTime $dateEmbauche
     *
     * @return $this
     */
    public function setDateEmbauche($dateEmbauche)
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @ORM\PreFlush
     */
    public function defineRole()
    {
        if ($this->type != null) {
            $this->setRoles(array($this->type));
        }

    }

    /**
     * Add lesFich
     *
     * @param FicheFrais $lesFich
     *
     * @return $this
     */
    public function addLesFich(FicheFrais $lesFich)
    {
        $this->lesFiches[] = $lesFich;

        return $this;
    }

    /**
     * Remove lesFich
     *
     * @param FicheFrais $lesFich
     */
    public function removeLesFich(FicheFrais $lesFich)
    {
        $this->lesFiches->removeElement($lesFich);
    }

    /**
     * Get lesFiches
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getLesFiches()
    {
        return $this->lesFiches;
    }

    /**
     * @return string
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * @param string $number
     */
    public function setNumber($number)
    {
        $this->number = $number;
    }

    /**
     * Tells if the the given user is this user.
     *
     * Useful when not hydrating all fields.
     *
     * @param null|UserInterface $user
     *
     * @return boolean
     */
    public function isUser(UserInterface $user = null)
    {
        return $user === $this;
    }
}

src/fraisBundle/Form/UtilisateurType.php
<?php

namespace fraisBundle\Form;

use fraisBundle\Entity\Utilisateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UtilisateurType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('adresse')
            ->add('cp')
            ->add('ville')
            ->add('dateEmbauche', 'date')
            ->add('type', 'choice', array(
                'choices' => Utilisateur::getRolesAvailable()
            ))
            ->add('enabled', 'checkbox', array(
                'label' => 'Compte activé',
                'required' => false,
            ));;
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }

    // For Symfony 2.x

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'fraisBundle\Entity\Utilisateur'
        ));
    }
}

src/fraisBundle/Controller/UtilisateurController.php
<?php

namespace fraisBundle\Controller;

use Doctrine\ORM\EntityManager;
use fraisBundle\Entity\Utilisateur;
use fraisBundle\Form\UtilisateurType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class UtilisateurController extends Controller
{

    /**
     * @return Response
     * @throws \Exception
     */
    public function listAction()
    {
        if (!$this->isGranted(Utilisateur::ROLE_ADMINISTRATEUR)) {
            throw $this->createAccessDeniedException();
        }
        $repo = $this->getDoctrine()->getRepository('fraisBundle:Utilisateur');


        return $this->render($this->getTemplateNamespace() . 'list.html.twig', array(
            "list" => $repo->findAll(),
        ));
    }

    /**
     * Return string of location of template like : AppBundle:MY_ENTITY_NAME
     * @return string
     */
    protected function getTemplateNamespace()
    {
        return 'fraisBundle:Utilisateur:';
    }

    /**
     * @param Request $request
     * @return Response
     */
    public function createAction(Request $request)
    {
        if (!$this->isGranted(Utilisateur::ROLE_ADMINISTRATEUR)) {
            throw $this->createAccessDeniedException();
        }

        $entity = new Utilisateur();

        $form = $this->createForm(new UtilisateurType(), $entity);

        $form
            ->add('save', SubmitType::class, array('label' => 'Ajouter'))
            ->add('back', ButtonType::class, array('label' => 'Retour'));

        $form->handleRequest($request);
        if ($form->isValid()) {

            $this->getEntityManager()->persist($entity);
            $this->getEntityManager()->flush();

            $this->addFlash("info", "L'utilisateur : " . $entity . " a été créé");

            if ($request->isXmlHttpRequest()) {
                $html = $this
                    ->render('fraisBundle:Utilisateur:ligne_user_content.html.twig', array('user' => $entity))
                    ->getContent();

                $response = array(
                    'data' => $html,
                );

                return new JsonResponse($response, 200);

            } else {

                return $this->redirectToList();
            }


        }


        return $this->render($this->getTemplateNamespace() . 'create.html.twig', array(
            'form' => $form->createView(),
            'entity' => $entity,
            'listRoute' => $this->getListRoute(),
            'templateNamespace' => $this->getTemplateNamespace(),

        ));
    }

    /**
     * @return EntityManager
     */
    protected function getEntityManager()
    {
        return $this->getDoctrine()->getManager();
    }

    /**
     * @return RedirectResponse
     */
    protected function redirectToList()
    {
        return $this->redirectToRoute($this->getListRoute());
    }

    /**
     * @return string
     */
    protected function getListRoute()
    {
        return 'frais_Utilisateur_list';

    }

    /**
     * @param Request $request
     * @param Utilisateur $entity
     * @return Response
     */
    public function updateAction(Request $request, Utilisateur $entity)
    {
        if (!$this->isGranted(Utilisateur::ROLE_ADMINISTRATEUR)) {
            throw $this->createAccessDeniedException();
        }

        $form = $this->createForm(new UtilisateurType(), $entity);

        $form
            ->add('save', SubmitType::class, array('label' => 'Mettre à jour'))
            ->add('back', ButtonType::class, array('label' => 'Retour'));

        $form->handleRequest($request);
        if ($form->isValid()) {


            $this->getEntityManager()->persist($entity);
            $this->getEntityManager()->flush();

            $this->addFlash("info", "L'utilisateur : " . $entity . " a été mis a jour");
            return $this->redirectToList();
        }

        return $this->render($this->getTemplateNamespace() . 'update.html.twig', array(
            'form' => $form->createView(),
            'entity' => $entity,
            'listRoute' => $this->getListRoute(),
            'templateNamespace' => $this->getTemplateNamespace(),
        ));
    }

    /**
     * @param Utilisateur $entity
     * @return RedirectResponse
     */
    public function deleteAction(Utilisateur $entity)
    {
        if (!$this->isGranted(Utilisateur::ROLE_ADMINISTRATEUR)) {
            throw $this->createAccessDeniedException();
        }

        $this->getEntityManager()->remove($entity);
        $this->getEntityManager()->flush();

        $this->addFlash("info", "L'utilisateur : " . $entity . " a été supprimé");

        return $this->redirectToList();
    }

    /**
     * @param Utilisateur $entity
     * @return Response
     */
    public function viewAction(Utilisateur $entity)
    {
        return $this->render($this->getTemplateNamespace() . 'view.html.twig', array(
            'entity' => $entity
        ));
    }
}

src/fraisBundle/Resources/views/Utilisateur/create.html.twig
{{ include("fraisBundle:Utilisateur:create_content.html.twig") }}


src/fraisBundle/Resources/views/Utilisateur/create_content.html.twig
<div class="uk-panel uk-container-center" style=" margin: 0 30px 15px 30px;">
    <div class="uk-width-medium-1-1 uk-form-horizontal">
        {% include templateNamespace~"formType.html.twig" with {'form': form} %}
    </div>
    <div class="uk-width-1-4"></div>
</div>

src/fraisBundle/Resources/views/Utilisateur/formType.html.twig
{{ form_start(form, { 'attr': {'class': 'uk-form-stacked ajouterUtilisateurform'}} ) }}
{% for key,item in form.children %}
    {% if key not in ['back', 'save'] %}
        {{ form_row(item) }}
    {% endif %}
{% endfor %}
<div class="uk-margin-top">
    <a href="{{ path(listRoute) }}">{{ form_widget(form.back) }}</a>
    {{ form_widget(form.save, { 'attr': {'class': 'uk-button-primary'}}) }}
</div>
{{ form_end(form) }}

src/fraisBundle/Resources/views/Utilisateur/ligne_user_content.html.twig
<tr>
    <td>{{ user.nom }} </td>
    <td>{{ user.prenom }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.rolesAvailable[ user.roles[0] ] }}</td>
    <td>
        <a href="{{ path('frais_Utilisateur_update', {'id': user.id} ) }}" class="btn-action uk-icon-pencil"></a>
        <a href="{{ path('frais_Utilisateur_delete', {'id': user.id} ) }}" class="btn-action uk-icon-remove"></a>
    </td>
</tr>

src/fraisBundle/Resources/views/Utilisateur/list.html.twig
{% extends '::base.html.twig' %}

{% set title = "Liste des utilisateurs" %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/components/search.gradient.min.css') }}" type="text/css"/>
{% endblock %}

{# Javascript #}
{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('js/components/search.min.js') }}"></script>
    <script type="application/javascript">
        $("#search").keyup(function () {
            _this = this;
            // Show only matching TR, hide rest of them
            $.each($("#table tbody tr"), function () {
                if ($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
                    $(this).hide();
                else
                    $(this).show();
            });
        });
    </script>
    <script>
        /*
         var modal = UIkit.modal(".modalSelector");

         if ( modal.isActive() ) {
         modal.hide();
         } else {
         modal.show();
         }
         */

        $('#my-id').on({

            'show.uk.modal': function () {
                //alert("ouverture");
            },

            'hide.uk.modal': function () {
                //   alert("fermeture");
            }
        });

        function submitAjouterUtlisateurForm(event) {
            // Eviter le comportement par défaut (soumettre le formulaire)
            event.preventDefault();

            var $this = $(this);
            var configAjax = {
                method: $this.attr('method'),
                url: "{{ path("frais_Utilisateur_create") }}",
                data: new FormData($this[0]),
                datatype: 'html',
                processData: false,
                contentType: false
            };
            console.log(configAjax);

            $.ajax(configAjax)
                    .done(function (response) {
                        //alert('done');
                        if (typeof response.data !== 'undefined') {

                            $('tbody.listeUtilisateurs').append(response.data);
                            $('#my-id').hide();


                        }
                    })
                    .fail(function (jqXHR, textStatus, errorThrown) {
                        alert('fail');
                        if (typeof jqXHR.responseJSON !== 'undefined') {
                            if (jqXHR.responseJSON.hasOwnProperty('form')) {
                                //$('#loginform').html(jqXHR.responseJSON.form);
                                $('#loginform').replaceWith(
                                        jqXHR.responseJSON.form
                                );
                            }
                        } else {
                            alert(errorThrown);
                        }

                    })
                    .always(function () {
                    });
        }
        //quand le formulaire est soumi
        $('.ajouterUtilisateurform').submit(submitAjouterUtlisateurForm);//callback

    </script>

{% endblock %}

{% block body %}
    <!-- This is the modal -->
    <div id="my-id" class="uk-modal">
        <div class="uk-modal-dialog">
            <a class="uk-modal-close uk-close"></a>
            {{ render(controller("fraisBundle:Utilisateur:create")) }}
        </div>
    </div>
    <form class="uk-search" data-uk-search="{source:'my-results.json'}">

        <input id="search" class="uk-search-field" type="search" placeholder="Chercher...">

        <div class="uk-dropdown uk-dropdown-search">
            <ul class="uk-nav uk-nav-search">...</ul>
        </div>

    </form>

    <a href="#my-id" data-uk-modal="{target:'#my-id'}" style="background: #0EC1F2 ;"
       class="uk-button-success uk-button uk-float-right"><i class="uk-icon-plus-circle"></i> Ajouter</a>

    <div class="uk-panel" style=" margin: 0 30px 15px 30px;">
        <table id="table" class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
            <thead>
            <tr>
                <th>Nom</th>
                <th>Prénom</th>
                <th>E-Mail</th>
                <th>Rôle</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody class="listeUtilisateurs">
            {% for user in list %}
                {{ include("fraisBundle:Utilisateur:ligne_user_content.html.twig", {'user' : user}) }}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

src/fraisBundle/Resources/views/Utilisateur/update.html.twig
{% extends '::base.html.twig' %}

{% set title = "Éditer" %}

{% block stylesheets %}
    {{ parent() }}
    {# <link rel="stylesheet" href="{{ asset('css/MY_NAME.css') }}" type="text/css"/> #}
{% endblock %}

{# Javascript #}
{% block javascripts %}
    {{ parent() }}
    {# <script type="text/javascript" src="{{ asset('js/FILENAME.js') }}"></script> #}
{% endblock %}

{% block body %}
    <div class="uk-panel uk-container-center" style=" margin: 0 30px 15px 30px;">
        <div class="uk-width-large-1-2 uk-width-medium-1-1 uk-container-center uk-form-horizontal">
            {% include templateNamespace~"formType.html.twig" with {'form': form} %}
        </div>
        <div class="uk-width-1-4"></div>
    </div>
{% endblock %}

src/fraisBundle/Resources/views/Utilisateur/view.html.twig
{% extends '::base.html.twig' %}

{% set title = "NAME HERE" %}

{% block stylesheets %}
    {{ parent() }}
    {# <link rel="stylesheet" href="{{ asset('css/MY_NAME.css') }}" type="text/css"/> #}
{% endblock %}

{# Javascript #}
{% block javascripts %}
    {{ parent() }}
    {# <script type="text/javascript" src="{{ asset('js/FILENAME.js') }}"></script> #}
{% endblock %}

{% block body %}
    entity : {{ entity }}
    nom : {{ entity.nom }}
{% endblock %}