src/fraisBundle/Entity/FicheFrais.php
<?php

namespace fraisBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\UserInterface;
use fraisBundle\Ref\EtatFiche;
use fraisBundle\Ref\EtatLigne;
use IntlDateFormatter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * FicheFrais
 *
 * @ORM\Table(name="fiche_frais",
 *      indexes={
 *          @ORM\Index(name="idx_annee_mois", columns={"date_action"})
 *      }
 * )
 * @ORM\Entity(repositoryClass="fraisBundle\Repository\FicheFraisRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class FicheFrais
{

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_action", type="date", nullable=false)
     */
    private $dateAction;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_creation", type="date", nullable=false)
     */
    private $dateCreation;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_modification", type="datetime", nullable=true)
     */
    private $dateModification;

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var Utilisateur
     *
     * @ORM\ManyToOne(targetEntity="fraisBundle\Entity\Utilisateur", inversedBy="lesFiches")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;

    /**
     * @var String EtatFiche
     *
     * @ORM\Column(name="etat", type="text", length=35)
     */
    private $etat;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="fraisBundle\Entity\Document", mappedBy="fiche", cascade={"persist"})
     */
    private $documents;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="fraisBundle\Entity\LigneForfait", mappedBy="ficheFrais", cascade={"persist"})
     */
    private $lesLignesForfaits;


    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="fraisBundle\Entity\LigneHorsForfait", mappedBy="ficheFrais", cascade={"persist"})
     */
    private $lesLignesHorsForfaits;

    /**
     * Constructor
     * @param UserInterface $user
     */

    /**
     * @var String Commentaire
     *
     * @ORM\Column(name="commentaire", type="text", nullable=true)
     */
    private $commentaire;

    public function __construct(UserInterface $user)
    {
        $this->lesLignesForfaits = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->lesLignesHorsForfaits = new ArrayCollection();
        $this->dateCreation = new \DateTime();

        $this->utilisateur = $user;
        $this->setEtat(EtatFiche::CREATE);
    }

    /**
     * Get dateModification
     *
     * @return \DateTime
     */
    public function getDateModification()
    {
        return $this->dateModification;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get utilisateur
     *
     * @return Utilisateur
     */
    public function getUtilisateur()
    {
        return $this->utilisateur;
    }

    /**
     * Get etat
     *
     * @return EtatFiche
     */
    public function getEtat()
    {
        return $this->etat;
    }


    /**
     * Set etat
     *
     * @param String $etat
     *
     * @return $this
     */
    public function setEtat($etat)
    {
        if (!in_array($etat, EtatFiche::getList())) {
            throw new \LogicException('This State is not valid');
        }

        $this->etat = $etat;

        return $this;
    }

    /**
     * Add lesLignesForfait
     *
     * @param LigneForfait $lesLignesForfait
     *
     * @return FicheFrais
     */
    public function addLesLignesForfait(LigneForfait $lesLignesForfait)
    {
        $lesLignesForfait->setFicheFrais($this);
        $this->lesLignesForfaits[] = $lesLignesForfait;

        return $this;
    }

    /**
     * Remove lesLignesForfait
     *
     * @param LigneForfait $lesLignesForfait
     */
    public function removeLesLignesForfait(LigneForfait $lesLignesForfait)
    {
        $this->lesLignesForfaits->removeElement($lesLignesForfait);
    }

    /**
     * Get lesLignesForfaits
     *
     * @return LigneForfait[]|ArrayCollection
     */
    public function getLesLignesForfaits()
    {
        return $this->lesLignesForfaits;
    }

    /**
     * Add lesLignesHorsForfait
     *
     * @param LigneHorsForfait $lesLignesHorsForfait
     *
     * @return FicheFrais
     */
    public function addLesLignesHorsForfait(LigneHorsForfait $lesLignesHorsForfait)
    {
        $lesLignesHorsForfait->setFicheFrais($this);
        $this->lesLignesHorsForfaits[] = $lesLignesHorsForfait;

        return $this;
    }

    /**
     * Remove lesLignesHorsForfait
     *
     * @param LigneHorsForfait $lesLignesHorsForfait
     */
    public function removeLesLignesHorsForfait(LigneHorsForfait $lesLignesHorsForfait)
    {
        $this->lesLignesHorsForfaits->removeElement($lesLignesHorsForfait);
    }

    /**
     * Get lesLignesHorsForfaits
     *
     * @return LigneHorsForfait[]|ArrayCollection
     */
    public function getLesLignesHorsForfaits()
    {
        return $this->lesLignesHorsForfaits;
    }


    /**
     * @ORM\PreUpdate
     */
    public function onPreUpdate()
    {
        $this->dateModification = new \DateTime();
    }

    /**
     * Get dateCreation
     *
     * @return \DateTime
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }

    public function getCommentaire()
    {
        return $this->commentaire;
    }

    public function setCommentaire($commentaire)
    {
        $this->commentaire = $commentaire;
        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        $fmt = new IntlDateFormatter("fr_FR", IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE,
            'Europe/Paris', IntlDateFormatter::GREGORIAN, "MMMM y");

        return "Fiche du mois de " . $fmt->format($this->dateAction);
    }


    /**
     * Add document
     *
     * @param Document $document
     *
     * @return FicheFrais
     */
    public function addDocument(Document $document)
    {
        $this->documents[] = $document;

        return $this;
    }

    /**
     * Remove document
     *
     * @param Document $document
     */
    public function removeDocument(Document $document)
    {
        $this->documents->removeElement($document);
    }

    /**
     * Get documents
     *
     * @return ArrayCollection
     */
    public function getDocuments()
    {
        return $this->documents;
    }

    /**
     * @return \DateTime
     */
    public function getDateAction()
    {
        return $this->dateAction;
    }

    /**
     * @param \DateTime $dateAction
     * @return $this
     */
    public function setDateAction(\DateTime $dateAction)
    {
        $dateAction->modify('first day of this month');
        $this->dateAction = $dateAction;

        return $this;
    }

    public function getMontant()
    {
        return $this->getMontantForfait() + $this->getMontantHorsForfait();
    }

    public function getMontantForfait()
    {
        $total = 0;
        /** @var LigneForfait $ligne */
        foreach ($this->lesLignesForfaits as $ligne) {
            $total += $ligne->getMontant();
        }
        return $total;
    }

    public function getMontantHorsForfait()
    {
        $total = 0;

        /** @var LigneHorsForfait $ligne */
        foreach ($this->lesLignesHorsForfaits as $ligne) {
            $total += $ligne->getMontant();
        }
        return $total;
    }

    public function getMontantValide()
    {
        return $this->getMontantForfaitValide() + $this->getMontantHorsForfaitValide();
    }

    public function getMontantForfaitValide()
    {
        $total = 0;

        /** @var LigneHorsForfait $ligne */
        foreach ($this->lesLignesForfaits as $ligne) {
            if ($ligne->isValid() === true) {
                $total += $ligne->getMontant();
            }
        }
        return $total;
    }

    public function getMontantHorsForfaitValide()
    {
        $total = 0;

        /** @var LigneHorsForfait $ligne */
        foreach ($this->lesLignesHorsForfaits as $ligne) {
            if ($ligne->isValid() === true) {
                $total += $ligne->getMontant();
            }
        }
        return $total;
    }

    public function checkState()
    {
        $isValid = true;
        /** @var LigneForfait $line */
        foreach (array_merge($this->lesLignesForfaits->toArray(), $this->lesLignesHorsForfaits->toArray()) as $line) {
            if ($line->getEtat() == EtatLigne::CREATE) {
                $isValid = false;
                break;
            }
        }

        if (true === $isValid) {
            $this->setEtat(EtatFiche::VALID);
        }
    }
}

src/fraisBundle/Controller/ComptableController.php
<?php

namespace fraisBundle\Controller;

use fraisBundle\Entity\FicheFrais;
use fraisBundle\Entity\Utilisateur;
use fraisBundle\Form\FindUtilisateurType;
use fraisBundle\Ref\EtatLigne;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;

class ComptableController extends Controller
{
    const CAN_VALID = true;
    const CAN_NOT_VALID = false;

    public function indexAction()
    {
        $state = $this->checkState();

        $fiches = $this->get('frais.fiche_frais_manager')->getListFicheSeekValid();

        return $this->render('fraisBundle:Comptable:index.html.twig', array(
            'state' => $state,
            'fiches' => $fiches,
        ));
    }

    private function checkState()
    {
        if (!$this->isGranted(Utilisateur::ROLE_COMPTABLE)) {
            throw $this->createAccessDeniedException();
        }

        $dateDebutSaisieFrais = $this->getParameter('date_debut_validation_frais');
        $dateFinSaisieFrais = $this->getParameter('date_fin_validation_frais');
        //state
        $now = new \DateTime('now');
        $day = $now->format('j');
        return ($day >= $dateDebutSaisieFrais && $day <= $dateFinSaisieFrais) ? self::CAN_VALID : self::CAN_NOT_VALID;
    }

    public function manageLineAction($type, $id, $state)
    {
        $this->checkState();
        $manager = $this->get('frais.fiche_frais_manager');
        $em = $this->getDoctrine()->getManager();
        $line = null;

        if ("f" === $type) {
            $line = $em->getRepository('fraisBundle:LigneForfait')->find($id);
        } elseif ("hf" === $type) {
            $line = $em->getRepository('fraisBundle:LigneHorsForfait')->find($id);
        }

        if (null === $line) {
            throw $this->createNotFoundException();
        }

        if (false === in_array($state, EtatLigne::getList())) {
            throw new \LogicException('this state is not supported : ' . $state);
        }


        $baseFiche = $line->getFicheFrais();
        if ($type == "hf" and $state == EtatLigne::WAIT_DOCUMENTS) {
            $targetFiche = $manager->getCurrentFiche($line->getFicheFrais()->getUtilisateur());
            $line->setFicheFrais($targetFiche);
            $em->persist($targetFiche);
        }


        $line->setEtat($state);
        $baseFiche->checkState();
        $em->flush();

        $this->addFlash('success', 'L\'état a été changer.');

        return $this->redirectToRoute('frais_compta_view_fiche', array(
            'id' => $baseFiche->getId(),
        ));
    }

    public function showAction(FicheFrais $fiche)
    {
        $this->checkState();
        $manager = $this->get('frais.fiche_frais_manager');


        return $this->render('fraisBundle:Comptable:show.html.twig', array(
            'listFiche' => $manager->getListFicheOfYear($fiche->getUtilisateur()),
            'currentFiche' => $fiche,
        ));
    }


    public function historyAction(Request $request)
    {
        $manager = $this->get('frais.fiche_frais_manager');
        $form = $this->createForm(FindUtilisateurType::class);
        $form->add('ok', SubmitType::class);

        $form->handleRequest($request);
        if ($form->isValid()) {
            $user = $form->get('user')->getData();
            $last = $manager->getLastFiche($user);

            if ($last === null) {
                $this->addFlash('danger', 'L\'utilisateur n\'as de fiche.');
            } else {
                return $this->redirectToRoute('frais_compta_view_fiche', array('id' => $last->getId()));
            }
        }

        return $this->render('fraisBundle:Comptable:history.html.twig', array(
            'form' => $form->createView(),
        ));
    }
}

src/fraisBundle/Resources/views/Comptable/history.html.twig
{% extends "fraisBundle:Comptable:layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}


{% block javascripts %}
    {{ parent() }}
{% endblock %}


{% block body %}
    <div class="uk-text-center">
        {{ form_start(form) }}
        <h1>Choisir l'utilisateur : </h1>
        {{ form_widget(form.user) }}
        {{ form_widget(form.ok) }}
        {{ form_end(form) }}
    </div>
{% endblock %}

src/fraisBundle/Resources/views/Comptable/index.html.twig
{% extends "fraisBundle:Comptable:layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
{% endblock %}


{% block javascripts %}
    {{ parent() }}
{% endblock %}


{% block body %}
    <h3>Liste des fiches a valider</h3>
    {% if state is constant('fraisBundle\\Controller\\ComptableController::CAN_VALID') %}
        <table class="uk-table uk-table-striped">
            <thead>
            <tr>
                <th>Utilisateur</th>
                <th>Ligne au Fofait</th>
                <th>Ligne hors forfait</th>
                <th>Pièce jointe</th>
                <th>Total</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for fiche in fiches %}
                <tr>
                    <td>{{ fiche.utilisateur }}</td>
                    <td>{{ fiche.lesLignesForfaits|length }}</td>
                    <td>{{ fiche.lesLignesHorsForfaits|length }}</td>
                    <td>{{ fiche.documents|length }}</td>
                    <td>{{ fiche.montant }}€</td>
                    <td><a href="{{ path('frais_compta_view_fiche', {'id': fiche.id}) }}"
                           class="uk-button uk-button-primary uk-button-mini">Consulter</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% elseif state is constant('fraisBundle\\Controller\\ComptableController::CAN_NOT_VALID') %}
        <p>Vous ne pouvez valider aucun frais durant cette periode ! Les frais ce valide
            du {{ date_debut_validation_frais }} au {{ date_fin_validation_frais }}</p>
    {% else %}
        <p>Case not excepted</p>
    {% endif %}
{% endblock %}

src/fraisBundle/Resources/views/Comptable/layout.html.twig
{% extends '::base.html.twig' %}


{% block subMenu %}
    <li><a id="elementMenu" href="{{ path('frais_compta_accueil') }}"><i class="uk-icon-cogs"></i> A traiter</a></li>
    <li><a id="elementMenu" href="{{ path('frais_compta_history') }}"><i class="uk-icon-history"></i> Historique</a>
    </li>
{% endblock %}

src/fraisBundle/Resources/views/Comptable/show.html.twig
{% extends "fraisBundle:Comptable:layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .uk-panel-box {
            background: none;
            border: none;
        }

        #mainMenu {
            padding-bottom: 50px;
        }
    </style>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
{% endblock %}

{% block flash %}
{% endblock %}

{% block body %}
    <div class="uk-width-medium-8-10 uk-container-center">
        <div class="uk-grid">
            <div class="uk-width-8-10">
                    <div class="fiche_base">
                        <div class="uk-panel uk-panel-block fiche_header">
                            <h3>{{ currentFiche }}</h3>
                        </div>
                        <div id="fiche_content">
                            {% for label, flashes in app.session.flashbag.all %}
                                {% for flash in flashes %}
                                    <div class="uk-margin-right uk-margin-left uk-alert uk-alert-{{ label }}">
                                        {{ flash }}
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            <div class="uk-grid uk-margin-large-bottom">
                                <div class="uk-width-1-1 ">
                                    <dl class="uk-description-list-horizontal">
                                        <dt>Utilisateur :</dt>
                                        <dd>{{ currentFiche.utilisateur }}</dd>

                                        <dt>Etat</dt>
                                        <dd>{{ currentFiche.etat }}</dd>

                                        <dt>Montant Total :</dt>
                                        <dd>{{ currentFiche.montant }}€</dd>

                                        <dt>Montant Validé :</dt>
                                        <dd>{{ currentFiche.montantValide }}€</dd>
                                    </dl>
                                    <blockquote>
                                        <p>Forfait</p>
                                    </blockquote>
                                    <table class="uk-table">
                                        <thead>
                                        <tr class="uk-text-upper">
                                            <th>Date</th>
                                            <th>Forfait</th>
                                            <th>Quantité</th>
                                            <th>Montant Total</th>
                                            <th>Etat</th>
                                            <th style="width: 150px;"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for ligneForfait in currentFiche.lesLignesForfaits %}
                                            <tr class="uk-table-middle">
                                                <td>{{ ligneForfait.dateCreation | date('d/m/Y') }}</td>
                                                <td>{{ ligneForfait.idFraisForfait.region }}
                                                    > {{ ligneForfait.idFraisForfait.libelle }}</td>
                                                <td>{{ ligneForfait.quantite }}</td>
                                                <td>{{ ligneForfait.montant }}€</td>
                                                <td>{{ ligneForfait.etat }}</td>
                                                <td>
                                                    {% if currentFiche.etat == constant('\\fraisBundle\\Ref\\EtatFiche::CLOSE') and (
                                                    ligneForfait.etat == constant('\\fraisBundle\\Ref\\EtatLigne::CREATE') or
                                                    ligneForfait.etat == constant('\\fraisBundle\\Ref\\EtatLigne::WAIT_DOCUMENTS')
                                                    ) %}
                                                        <a href="{{ path('frais_compta_manage_line_forfait', {
                                                            'id': ligneForfait.id,
                                                            'state': constant('\\fraisBundle\\Ref\\EtatLigne::VALID')
                                                        }) }}" title="Valider" class="uk-button uk-button-success"><i
                                                                    class="uk-icon-check"></i></a>

                                                        <a href="{{ path('frais_compta_manage_line_forfait', {
                                                            'id': ligneForfait.id,
                                                            'state': constant('\\fraisBundle\\Ref\\EtatLigne::REFUSE')
                                                        }) }}" title="Refuser" class="uk-button uk-button-danger"><i
                                                                    class="uk-icon-remove"></i></a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td class="uk-text-center" colspan="5">Aucune ligne de frais n'a été
                                                    saisie
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                    <br/><br/><br/>

                                    <blockquote>
                                        <p>Hors-Forfait</p>
                                    </blockquote>
                                    <table class="uk-table">
                                        <thead>
                                        <tr class="uk-text-upper">
                                            <th>Date</th>
                                            <th>Libellé</th>
                                            <th>Montant</th>
                                            <th>Etat</th>
                                            <th style="width: 150px;"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for ligneHorsForfait in currentFiche.lesLignesHorsForfaits %}
                                            <tr class="uk-table-middle">
                                                <td>{{ ligneHorsForfait.dateCreation | date('d/m/Y') }}</td>
                                                <td>{{ ligneHorsForfait.libelle }}</td>
                                                <td>{{ ligneHorsForfait.montant }}</td>
                                                <td>{{ ligneHorsForfait.etat }}</td>
                                                <td>
                                                    {% if currentFiche.etat == constant('\\fraisBundle\\Ref\\EtatFiche::CLOSE') and (
                                                    ligneHorsForfait.etat == constant('\\fraisBundle\\Ref\\EtatLigne::CREATE') or
                                                    ligneHorsForfait.etat == constant('\\fraisBundle\\Ref\\EtatLigne::WAIT_DOCUMENTS')
                                                    ) %}
                                                        <a href="{{ path('frais_compta_manage_line_hors_forfait', {
                                                            'id': ligneHorsForfait.id,
                                                            'state': constant('\\fraisBundle\\Ref\\EtatLigne::VALID')
                                                        }) }}" title="Valider" class="uk-button uk-button-success"><i
                                                                    class="uk-icon-check"></i></a>

                                                        <a href="{{ path('frais_compta_manage_line_hors_forfait', {
                                                            'id': ligneHorsForfait.id,
                                                            'state': constant('\\fraisBundle\\Ref\\EtatLigne::REFUSE')
                                                        }) }}" title="Refuser" class="uk-button uk-button-danger"><i
                                                                    class="uk-icon-remove"></i></a>

                                                        <a href="{{ path('frais_compta_manage_line_hors_forfait', {
                                                            'id': ligneHorsForfait.id,
                                                            'state': constant('\\fraisBundle\\Ref\\EtatLigne::WAIT_DOCUMENTS')
                                                        }) }}" title="Reporter au mois suivant"
                                                           class="uk-button uk-button-primary"><i
                                                                    class="uk-icon-arrow-right"></i></a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% else %}
                                            <tr>
                                                <td class="uk-text-center" colspan="5">Aucune ligne de frais n'a été
                                                    saisie
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="uk-margin-large-top uk-width-1-1">
                                <blockquote>
                                    <p>Pièces justificatives</p>
                                </blockquote>
                                <table class="uk-table">
                                    <thead>
                                    <tr class="uk-text-upper">
                                        <th>Nom du document</th>
                                        <th>Date d'ajout</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for document in currentFiche.documents %}
                                        <tr class="uk-table-middle">
                                            <td>
                                                <a href="{{ vich_uploader_asset(document, 'fichier') }}">{{ document.nom }}</a>
                                            </td>
                                            <td>
                                                {{ document.dateModification|localizeddate('medium', 'none') }}
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="2">Aucune pièce justificative</td>
                                        </tr>
                                    {% endfor %}
                                    {% if currentFiche.etat == constant('\\fraisBundle\\Ref\\EtatFiche::CREATE') %}
                                        {{ form_start(formDocument) }}
                                        <tr class="uk-table-middle">
                                            <td>{{ form_widget(formDocument.fichier) }}</td>
                                            <td>{{ form_widget(formDocument.submit, {'attr': {'class': 'uk-padding-remove uk-icon-button uk-icon-download'} }) }}</td>
                                        </tr>
                                        {{ form_end(formDocument) }}
                                    {% endif %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="uk-margin-large-top uk-width-1-1 ">
                                <blockquote>
                                    <p>Commentaire</p>
                                </blockquote>
                                <p>{{ currentFiche.commentaire|nl2br }}</p>
                            </div>
                        </div>
                    </div>
            </div>

            <!-- Navigation -->
            <div id="fiche_nav" class="uk-width-large-2-10 uk-visible-large">

                <ul class="uk-nav uk-nav-side">
                    <li class="uk-text-center">Liste des fiches de frais</li>
                    {% for fiche in listFiche %}
                        {% if fiche == currentFiche %}
                            <li class="uk-active">
                        {% else %}
                            <li>
                        {% endif %}
                        <a href="{{ path('frais_compta_view_fiche', {'id': fiche.id}) }}">{{ fiche }}
                            <span id="etat" class="uk-badge uk-badge-success uk-float-right">{{ fiche.etat }}</span>
                        </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}